Better version support
AttilaTheFun/SwaggerParser pull request #23
Opened 2017-07-07 17:14 UTC by yonaskolb

This fixes cases where version is parsed as a double instead of a string

2017-07-07 23:56 UTC, AttilaTheFun commented on Sources/Version.swift
> +        let string = "\(value)"
how about:
```
guard let value = value, 
    let string = (value as? LosslessStringConvertible).map(String.init) else
{
    return nil
}
```

2017-07-07 23:57 UTC, AttilaTheFun requested changes
Just throwing the value into a string seems a little error prone. How about we use the handy LosslessStringConvertible protocol to make sure the type has a legitimate string representation.

2017-07-08 08:29 UTC, yonaskolb commented
Oh I didn't know about that protocol, cool, will do. 
I originally thought something like that would just over complicate things, as the actual validation and parsing of the string happens below.

2017-07-09 00:44 UTC, AttilaTheFun approved these changes
Looks good :)

2017-07-09 07:56 UTC, merged

2017-07-09 09:27 UTC, AttilaTheFun commented
@yonaskolb FYI I realized that the LosslessStringConvertible protocol doesn't work here because the 'value' that comes from the mapper is actually an NSObject that only gets bridged to swift if you cast it. I'm updating this in master to work with String, Float, Double or Int values.

2017-07-09 09:33 UTC, yonaskolb commented
Ok, cool. Thanks