Extract metadata
AttilaTheFun/SwaggerParser pull request #26
Opened 2017-07-08 13:24 UTC by yonaskolb

This extracts the metadata property out of each Schema and Items case. This:

- makes accessing the metadata property easier without switches or casing of enums (especially useful for templates or anything that needs easy access)
- cleans up a lot of reduntant code

The enums are now moved into their own property, and just contain data relevant to them. It does change the public api slightly by making the schema enum be `schema.type` instead of `schema`

What do you think?

2017-07-08 23:10 UTC, AttilaTheFun reviewed
I very much like this direction - I think it's definitely much easier to access the metadata this way. However, it is a breaking change to the API, so I'll definitely have to bump the minor version for this.

2017-07-09 00:42 UTC, AttilaTheFun requested changes
I left a few comments, but I really like this direction. Given that it's a breaking API change, let's try to merge all the non-breaking PRs first, pin a version, and then merge this + bump to 0.4.0

2017-07-09 00:42 UTC, AttilaTheFun commented on Sources/AllOfSchema.swift
>                             abstract: self.abstract)
Now these fit on one line, you can wrap abstract up into the previous line.

2017-07-09 00:42 UTC, AttilaTheFun commented on Sources/ArrayItem.swift
> +        return ArrayItem(items: try self.items.build(swagger),
I think you can wrap this to two lines? I set the page guide to 110 characters

2017-07-09 00:42 UTC, AttilaTheFun commented on Sources/ArraySchema.swift
> +        return ArraySchema(items: items, minItems: self.minItems,
Two lines?

2017-07-09 00:42 UTC, AttilaTheFun commented on Sources/IntegerItem.swift
> +        return IntegerItem(format: self.format,
Two lines?

2017-07-09 00:42 UTC, AttilaTheFun commented on Sources/Items.swift
> +        return Items(metadata: metadata, type: type)
I think you can inline those:
```
return Items(metadata: try metadataBuilder.build(swagger), 
    type: try metadataBuilder.build(swagger))
```

2017-07-09 00:42 UTC, AttilaTheFun commented on Sources/Items.swift
> +        let dataType = DataType(map: map)
If you're not doing anything with the dataType outside the switch statement I think you can just inline it.
```
switch DataType(map: map) {
```

2017-07-09 00:42 UTC, AttilaTheFun commented on Sources/NumberItem.swift
> +        return NumberItem(format: self.format,
Two lines?

2017-07-09 00:42 UTC, AttilaTheFun commented on Sources/ObjectSchema.swift
> +        return ObjectSchema(required: self.required,
I'd re-wrap this at 110 characters.

2017-07-09 00:42 UTC, AttilaTheFun commented on Sources/Metadata.swift
> +    public init(map: Map) {
I don't want to leak ObjectMapper to consumers of the library - let's make this method internal.

2017-07-09 00:42 UTC, AttilaTheFun commented on Sources/Schema.swift
> +    public init(map: Map) throws {
You should not have a public initializer on an internal struct

2017-07-09 00:42 UTC, AttilaTheFun commented on Sources/Schema.swift
>      public init(map: Map) throws {
~~public~~

2017-07-10 16:38 UTC, n8chur commented
This is great! Nice work @yonaskolb 👍

2017-07-11 17:37 UTC, AttilaTheFun commented
@yonaskolb Do you know when you'll have time to address these comments?

2017-07-11 17:54 UTC, yonaskolb commented
@AttilaTheFun not at the moment. I may let you check out the branch and make any code style choices you wish 👍

2017-07-11 18:12 UTC, AttilaTheFun commented
Okay, would it be possible to create a branch like AttilaTheFun:extract_metadata, change the base for this PR, and merge it into there? Then I can make these changes on that branch.

2017-07-11 20:12 UTC, yonaskolb commented on Sources/Metadata.swift
> +    public init(map: Map) {
`Initializer 'init(map:)' must be declared public because it matches a requirement in public protocol 'ImmutableMappable'`

2017-07-11 20:13 UTC, yonaskolb commented
I just made the changes - easier :)

2017-07-11 20:17 UTC, AttilaTheFun commented
Awesome! I'll check it out :)

2017-07-11 20:47 UTC, AttilaTheFun commented on Sources/Metadata.swift
> +    public init(map: Map) {
Ah, okay :/
I guess that issue will go away with the Codable refactor

2017-07-11 20:54 UTC, AttilaTheFun approved these changes
Looks good - I pushed a few minor changes if you could check those over before you merge.

2017-07-12 05:24 UTC, AttilaTheFun commented
I'm gonna go ahead and merge this so I can rebase my other PR off of it. If you have any issues, feel free to open an issue / another pr.

2017-07-12 05:25 UTC, merged