`allOf` support
AttilaTheFun/SwaggerParser pull request #6
Opened 2017-05-26 19:40 UTC by n8chur

Additionally moves test fixture to a separate file, rather than being defined in-line.

2017-05-28 00:25 UTC, AttilaTheFun requested changes
Looks pretty good overall!

2017-05-28 00:25 UTC, AttilaTheFun commented on Sources/AllOfSchema.swift
> +
I usually don't add extra newlines unless there is a comment.
E.g.:

```
public struct AllOfSchema {
    public let metadata: Metadata
    public let schemas: [Schema]
}
```

or

```
/// Something about AllOfSchema
public struct AllOfSchema {
    /// Something about metadata
    public let metadata: Metadata

    /// Something about schemas
    public let schemas: [Schema]
}
```

2017-05-28 00:25 UTC, AttilaTheFun commented on Sources/AllOfSchema.swift
> +        let allOf: [[String:Any]] = try map.value("allOf")
I don't believe this is necessary. [Mappable] is also Mappable.
I believe you can just do:
```
schemaBuilders = try map.value("allOf")
```

2017-05-28 00:25 UTC, AttilaTheFun commented on Sources/AllOfSchema.swift
> +        let schemas = try schemaBuilders.map {try $0.build(swagger)}
Spacing around curly braces:
```
{ try $0.build(swagger) }
```

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/Fixtures/test_all_of.json
> +      "discriminator": "test_type",
You've added a discriminator here but not support for it. Do you want to add that in a separate PR?
If it's not going to be added in this PR I would remove the line from the fixture.

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> -private let uberJSONString = "{\"swagger\":\"2.0\",\"info\":{\"title\":\"Uber API\",\"description\":\"Move your app forward with the Uber API\",\"version\":\"1.0.0\"},\"host\":\"api.uber.com\",\"sche
Thanks for setting up the fixtures! They're much easier to use :)

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        let jsonString = try! NSString(contentsOfFile: url.path, encoding: String.Encoding.utf8.rawValue) as String
You can just use 
```String.init(contentsOf: URL, encoding: String.Encoding)```

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        let swagger = try! Swagger(JSONString: jsonString)
I would prefer we didn't crash the test if any one of these try! calls failed.
Can you wrap the whole test in a try / catch block and just print the error + fail the test in that case?

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        let url = testFixtureFolder.appendingPathComponent("test_all_of.json")
How about making these lines into a private helper function?
```
private func loadFixture(named fileName: String) throws -> String {
    let url = testFixtureFolder.appendingPathComponent(fileName)
    return try String(contentsOfFile: url.Path, encoding: .utf8)
}
```

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +            case .object(let baseSchema) = baseDefinition.structure else {
When you have a multi-line guard statement, break the trailing curly brace onto the next line so Xcode doesn't double-indent the next line.

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +            case .object(let baseSchema) = baseDefinition.structure else {
If you want to get fancy...
```
guard case .some(.object(let baseSchema)) = swagger.definitions.first(where: {$0.name == "TestAllOfBase"}) else {
```

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +                XCTFail("TestAllOfBase is not an object schema."); return
De-indent this

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        swagger.definitions.validate(testAllOfChild: "TestAllOfFoo", withPropertyNames: ["foo"])
I think all three of these could be separate tests.

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +                    guard case .object(let baseSchema) = structure.structure else {fatalError()}
Would prefer we don't crash in test cases. Instead can we throw the error up to the top level test case and wrap it in a try/catch? Then we can catch + print the error and fail the test.

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        if case .allOf(let schema) = definition.structure {
Let's call this allOfSchema

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        return (base: base, child: child)
How about we make base and child implicitly unwrapped optionals and then throw an error if either is nil before we return?

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        }
I like how you structured this with the series of guard statements.
A couple of nits:
- Newline after each closing curly preceding a statement.
- Let's avoid combining statements into one line like this - semicolons are the devil!
- XCTFail is a void function. You can just do:
```
return XCTFail(...)
```

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        XCTAssertEqual(childAllOf.schemas.count, 2)
\n

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +            case .object(let childsParentSchema) = childsParentStructure.structure else {
Opening curly on newline, de-indent

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        SwaggerParserTests.validate(thatSchema: childsParentSchema, named: parentName, hasRequiredProperties: parentProperties)
\n

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +    class func validate(testAllOfBaseSchema schema: ObjectSchema) {
I don't think these functions need to be class functions. I'd honestly just make them private functions (defined at file scope).

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        SwaggerParserTests.validate(thatSchema: childSchema, named: childName, hasRequiredProperties: childProperties)
\n

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +            case .object(let childSchema) = child else {
curly on newline, de-indent

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        let testAllOfChild = self.first(where: {$0.name == name})!
Let's not do force unwraps - I like what you were doing earlier with the guard statements where the else has XCTFail

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        XCTAssertEqual(structure.name, objectName)
\n

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        return (base: base, child: child)
Also newline before statement

2017-05-28 00:25 UTC, AttilaTheFun commented on Sources/AllOfSchema.swift
> +    public let schemas: [Schema]
I think we should call this subschemas or something less generic

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +                switch $0 {
Please don't use $0 if your closure is more than one line.
```
allOfSchema.subschemas.forEach { schema in
    switch schema {
    ...
    }
}
```

2017-05-28 00:25 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +                default: fatalError()
I dislike putting statements on the same line as the colon. Also let's not fatalError() - how about throwing an error or doing XCTFail

2017-05-28 00:28 UTC, AttilaTheFun commented
@n8chur thanks! I just finished going through your PR and leaving comments. It looked pretty good overall, mostly just stylistic / nitpicky things. FYI the reason I don't like crashing in tests is that once you have a decent suite of tests, if one of the early ones crashes it doesn't end up running your full test suite.

2017-05-28 02:39 UTC, yonaskolb commented
Just thought I'd chime in here. You can also mark a test as throws and XCTest will automatically fail if something in the test throws. Saves you from try catching, and means you can easily mark any helper functions as throws as well

2017-05-28 02:57 UTC, AttilaTheFun commented
@yonaskolb oh cool! Didn't know that. @n8chur we should definitely take advantage of that,

2017-05-30 16:45 UTC, n8chur commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +            case .object(let baseSchema) = baseDefinition.structure else {
That is fancy! I didn't realize you could do that. That being said I do think keeping them new line separated helps with readability.

2017-05-30 16:49 UTC, n8chur commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        swagger.definitions.validate(testAllOfChild: "TestAllOfFoo", withPropertyNames: ["foo"])
This test was intended to validate that the swagger.json file is being parsed correctly which implies that each object should be validated within this test. Should I break it out into a separate test per schema being parsed? 

If we do break them out, we may want to consider making separate test files for each feature. 

I feel like a BDD framework would make breaking things out more granularly easier to manage (with `context`s and `describe` scopes).

2017-05-30 16:50 UTC, n8chur commented
@yonaskolb That's awesome! Thanks for the tip!

2017-05-31 08:53 UTC, AttilaTheFun requested changes
Looking good! I just added a few more comments, mostly style related. I would refactor the getBaseAndChildSchemas function like I proposed, however.

2017-05-31 08:53 UTC, AttilaTheFun commented on Sources/AllOfSchema.swift
> +
I prefer not to have trailing whitespace - can you remove this newline?

2017-05-31 08:53 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +                base = baseSchema
Can you add a newline after the closing curly brace before the next statement? If the curly brace ends the last statement in that scope the newline isn't necessary though. Also I don't think the newlines separating the case statements are necessary. They're already indented.

2017-05-31 08:53 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +fileprivate enum GetBaseAndChildSchemasError: Error {
let's add
```
case notAllOf
case incorrectSubschemaCount
```

2017-05-31 08:53 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +    guard base != nil else {
Don't use guard statements just to perform boolean checks - they should be unwrapping something usually.

2017-05-31 08:53 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +    if case .allOf(let allOfSchema) = definition.structure {
How about turning this into a guard statement that throws an error. Then you don't have to indent the rest of this if statement. I.e.:

```
guard case .allOf(let allOfSchema) = definition.structure else {
    throw GetBaseAndChildSchemasError.notAllOf
}

XCTAssertEqual(allOfSchema.subschemas.count, 2)

var base: ObjectSchema?
var child: ObjectSchema?

try allOfSchema.subschemas.forEach { subschema in
    switch subschema {
    case .object(let childSchema):
        child = childSchema
    case .structure(let structure):
        if case .object(let baseSchema) = structure.structure {
            base = baseSchema
        } else {
            throw GetBaseAndChildSchemasError.badSubschemaType(subschema)
        }
    default:
        throw GetBaseAndChildSchemasError.badSubschemaType(subschema)
    }
}

if let base = base, let child = child {
    return (base: base, child: child)
}

if base == nil {
    throw GetBaseAndChildSchemasError.missingBase
} else {
    throw GetBaseAndChildSchemasError.missingChild
}

2017-05-31 08:53 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        XCTAssertNotNil(schema.properties.first(where: {$0.key == property}))
This is O(n^2) - even if it is for a test. How about:
```
let keys = Set(schema.properties.keys)
properties.forEach { XCTAssert(keys.contains($0) }
```

2017-05-31 08:53 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +fileprivate func validate(thatParameter parameter: Parameter, named parameterName: String, isAnObjectNamed objectName: String, withPropertyName objectPropertyName: String) {
Same deal - let's not repeat the type information in the signature.
```
fileprivate func validate(that parameter: Parameter, ...
```

2017-05-31 08:53 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +    XCTAssertTrue(object.properties.contains(where: {$0.key == objectPropertyName}))
Do we need the where: here? Can't we just use the trailing closure syntax? In either case, let's put spaces inside the curly braces:
```
XCTAssertTrue(object.properties.contains { $0.key == objectPropertyName })

2017-05-31 08:53 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        XCTFail("\(childName) is not an allOf."); return
Please don't use the semicolon to connect statements - XCTFail is a void function anyways so you can:
```
return XCTFail("\(childName) is not an allOf.")
```

2017-05-31 08:53 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +        case .object(let childSchema) = child else
Can't you fit this all onto one line? Usually I set my guide at 110 characters (that's about the maximum Github can display cleanly in the diff view).
```
guard let child = childAllOf.subschemas.last, case .object(let childSchema) = child else {
```

2017-05-31 08:53 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +fileprivate func validate(thatDefinitions definitions: [Structure<Schema>], containsTestAllOfChild name: String, withPropertyNames propertyNames: [String]) throws {
Let's not repeat type in the signature:
```
fileprivate func validate(that definitions ...

2017-05-31 08:53 UTC, AttilaTheFun commented on Tests/SwaggerParserTests/SwaggerParserTests.swift
> +    guard let testAllOfChild = definitions.first(where: {$0.name == name}) else {
Spaces around the curly braces:
```
{ $0.name == name }

2017-05-31 18:12 UTC, AttilaTheFun approved these changes
Awesome! Thanks so much!

2017-05-31 18:13 UTC, merged

2017-05-31 18:30 UTC, n8chur commented
Thanks for viewing that and getting it merged!

2017-05-31 18:32 UTC, AttilaTheFun commented
No problem! Feel free to create another PR for the other stuff you mentioned